# Resampling Methods


## 5.3 Lab: Cross-Validation and the Bootstrap

In [1]:
import numpy as np
import statsmodels.api as sm
from ISLP import load_data
from ISLP.models import (ModelSpec as MS ,
summarize ,
poly)
from sklearn.model_selection import train_test_split

In [2]:
from functools import partial
from sklearn.model_selection import \
(cross_validate ,
KFold ,
ShuffleSplit)
from sklearn.base import clone
from ISLP.models import sklearn_sm

## 5.3.1 The Validation Set Approach

In [3]:
import numpy as np
import pandas as pd
Auto = pd.read_csv(r"C:\Users\user\OneDrive\Desktop\Data_Mining_Docs\ALL_CSV_FILES\Auto.csv")
Auto


mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [4]:
Auto_train , Auto_valid = train_test_split(Auto ,
test_size =196,
random_state =0)

In [5]:
import numpy as np
import pandas as pd
from ISLP.models import ModelSpec as MS
import statsmodels.api as sm

In [6]:
Auto_train['horsepower'] = Auto_train['horsepower'].replace('?', np.nan)
Auto_train = Auto_train.dropna(subset=['horsepower', 'mpg'])
Auto_train['horsepower'] = Auto_train['horsepower'].astype(float)
Auto_train['mpg'] = Auto_train['mpg'].astype(float)

In [7]:

hp_mm = MS(['horsepower'])
X_train = hp_mm.fit_transform(Auto_train)
X_train = pd.DataFrame(X_train).astype(float)
y_train = Auto_train['mpg'].astype(float)
model = sm.OLS(y_train, X_train)
results = model.fit()
print(results.summary())


                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.629
Model:                            OLS   Adj. R-squared:                  0.627
Method:                 Least Squares   F-statistic:                     331.8
Date:                Thu, 19 Jun 2025   Prob (F-statistic):           4.99e-44
Time:                        12:46:01   Log-Likelihood:                -587.00
No. Observations:                 198   AIC:                             1178.
Df Residuals:                     196   BIC:                             1185.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     40.3783      0.996     40.558      0.0

In [8]:
import numpy as np

Auto_valid['horsepower'] = Auto_valid['horsepower'].replace('?', np.nan)
Auto_valid = Auto_valid.dropna(subset=['horsepower', 'mpg'])
Auto_valid['horsepower'] = Auto_valid['horsepower'].astype(float)
Auto_valid['mpg'] = Auto_valid['mpg'].astype(float)
X_valid = hp_mm.transform(Auto_valid)
X_valid = np.array(X_valid).astype(float)
y_valid = Auto_valid['mpg'].astype(float)
valid_pred = results.predict(X_valid)
mse = np.mean((y_valid - valid_pred) ** 2)
print("Validation MSE:", mse)

Validation MSE: 26.074984326829124


In [9]:

import numpy as np
import pandas as pd
from ISLP.models import ModelSpec as MS
import statsmodels.api as sm

# --- 1. Clean training data ---
Auto_train['horsepower'] = Auto_train['horsepower'].replace('?', np.nan)
Auto_train = Auto_train.dropna(subset=['horsepower', 'mpg'])
Auto_train['horsepower'] = Auto_train['horsepower'].astype(float)
Auto_train['mpg'] = Auto_train['mpg'].astype(float)

# --- 2. Prepare training features and response ---
hp_mm = MS(['horsepower'])
X_train = hp_mm.fit_transform(Auto_train)
X_train = pd.DataFrame(X_train).astype(float)
y_train = Auto_train['mpg'].astype(float)

# --- 3. Fit OLS model ---
model = sm.OLS(y_train, X_train)
results = model.fit()
print(results.summary())

# --- 4. Clean validation data ---
Auto_valid['horsepower'] = Auto_valid['horsepower'].replace('?', np.nan)
Auto_valid = Auto_valid.dropna(subset=['horsepower', 'mpg'])
Auto_valid['horsepower'] = Auto_valid['horsepower'].astype(float)
Auto_valid['mpg'] = Auto_valid['mpg'].astype(float)

# --- 5. Prepare validation features and response ---
X_valid = hp_mm.transform(Auto_valid)
X_valid = np.array(X_valid).astype(float)
y_valid = Auto_valid['mpg'].astype(float)

# --- 6. Predict and evaluate ---
valid_pred = results.predict(X_valid)
mse = np.mean((y_valid - valid_pred) ** 2)
print("Validation MSE:", mse)



                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.629
Model:                            OLS   Adj. R-squared:                  0.627
Method:                 Least Squares   F-statistic:                     331.8
Date:                Thu, 19 Jun 2025   Prob (F-statistic):           4.99e-44
Time:                        12:46:01   Log-Likelihood:                -587.00
No. Observations:                 198   AIC:                             1178.
Df Residuals:                     196   BIC:                             1185.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     40.3783      0.996     40.558      0.0

In [10]:
pip install patsy


Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
import statsmodels.api as sm
from patsy import dmatrix

def evalMSE(feature_exprs, target, train, valid):
    X_train = dmatrix(feature_exprs[0], train)
    X_valid = dmatrix(feature_exprs[0], valid)
    
    y_train = train[target]
    y_valid = valid[target]
    
    model = sm.OLS(y_train, X_train).fit()
    
    y_pred = model.predict(X_valid)
    
    return np.mean((y_valid - y_pred)**2)


In [12]:
def poly(feature, degree):
    if degree == 1:
        return f"{feature}"
    else:
        return " + ".join([f"I({feature}**{d})" for d in range(1, degree + 1)])




In [13]:
MSE = np.zeros(3)
for idx, degree in enumerate(range(1, 4)):
    MSE[idx] = evalMSE([poly('horsepower', degree)],
                       'mpg',
                       Auto_train,
                       Auto_valid)
MSE


array([26.07498433, 20.36114057, 20.39102702])

In [17]:
import numpy as np

Auto['horsepower'] = Auto['horsepower'].replace('?', np.nan)
Auto = Auto.dropna(subset=['horsepower'])

Auto['horsepower'] = Auto['horsepower'].astype(float)
Auto['mpg'] = Auto['mpg'].astype(float)

C:\Users\user\AppData\Local\Temp\ipykernel_11684\2965306591.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Auto['horsepower'] = Auto['horsepower'].astype(float)
C:\Users\user\AppData\Local\Temp\ipykernel_11684\2965306591.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Auto['mpg'] = Auto['mpg'].astype(float)


In [18]:
from patsy import dmatrix
import statsmodels.api as sm
import numpy as np

def evalMSE(feature_exprs, target, train, valid):
    X_train = dmatrix(feature_exprs[0], train, return_type='dataframe')
    design_info = X_train.design_info
    X_valid = dmatrix(design_info, valid, return_type='dataframe')

    y_train = train[target]
    y_valid = valid[target]

    model = sm.OLS(y_train, X_train).fit()

    y_pred = model.predict(X_valid)
    return np.mean((y_valid - y_pred) ** 2)

In [19]:
from sklearn.model_selection import train_test_split
import numpy as np

Auto_train, Auto_valid = train_test_split(Auto, test_size=196, random_state=3)

MSE = np.zeros(3)

for idx, degree in enumerate(range(1, 4)):
    MSE[idx] = evalMSE([poly('horsepower', degree)],
                       'mpg',
                       Auto_train,
                       Auto_valid)

MSE


array([20.75540796, 16.94510676, 16.97437833])

## 5.3.2 Cross-Validation

In [23]:
from sklearn.base import BaseEstimator, RegressorMixin
import statsmodels.api as sm
from patsy import dmatrix

class StatsmodelsOLS(BaseEstimator, RegressorMixin):
    def __init__(self, formula):
        self.formula = formula

    def fit(self, X, y):
        X_design = dmatrix(self.formula, X, return_type='dataframe')
        self.model_ = sm.OLS(y, X_design).fit()
        self.design_info_ = X_design.design_info
        return self

    def predict(self, X):
        X_design = dmatrix(self.design_info_, X, return_type='dataframe')
        return self.model_.predict(X_design)

    def score(self, X, y):
        y_pred = self.predict(X)
        return -((y - y_pred) ** 2).mean()  # Return negative MSE for cross_validate


In [24]:
from sklearn.model_selection import cross_validate
import numpy as np

# Define model using horsepower as predictor
hp_model = StatsmodelsOLS("horsepower")

# X and Y setup
X = Auto.drop(columns=['mpg'])
Y = Auto['mpg']

# LOOCV (Leave-One-Out Cross-Validation)
cv_results = cross_validate(hp_model, X, Y, cv=X.shape[0])

# Compute cross-validation error (MSE)
cv_err = -np.mean(cv_results['test_score'])  # negate because score is -MSE
cv_err


24.23151351792923

## LOOCV for Degrees 1 to 3

In [26]:
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.model_selection import cross_validate
import statsmodels.api as sm
from patsy import dmatrix
import numpy as np

# Step 1: Define custom sklearn-compatible wrapper for statsmodels.OLS
class StatsmodelsOLS(BaseEstimator, RegressorMixin):
    def __init__(self, formula):
        self.formula = formula

    def fit(self, X, y):
        X_design = dmatrix(self.formula, X, return_type='dataframe')
        self.model_ = sm.OLS(y, X_design).fit()
        self.design_info_ = X_design.design_info
        return self

    def predict(self, X):
        X_design = dmatrix(self.design_info_, X, return_type='dataframe')
        return self.model_.predict(X_design)

    def score(self, X, y):
        y_pred = self.predict(X)
        return -((y - y_pred) ** 2).mean()  # return negative MSE

# Step 2: Prepare the data
X = Auto.drop(columns=['mpg'])
Y = Auto['mpg']

# Step 3: Loop over degrees 1 to 3 and store CV errors
cv_errors = []

for degree in range(1, 4):
    if degree == 1:
        formula = "horsepower"
    else:
        formula = " + ".join([f"I(horsepower**{d})" for d in range(1, degree + 1)])
    
    model = StatsmodelsOLS(formula)
    result = cross_validate(model, X, Y, cv=X.shape[0])
    cv_err = -np.mean(result['test_score'])  # negate because score is -MSE
    cv_errors.append(cv_err)

# Step 4: Print or return the results
for d, err in enumerate(cv_errors, start=1):
    print(f"Degree {d} CV Error (MSE): {err:.4f}")


Degree 1 CV Error (MSE): 24.2315
Degree 2 CV Error (MSE): 19.2482
Degree 3 CV Error (MSE): 19.3350


In [28]:
import numpy as np
import pandas as pd

# Replace '?' with np.nan
Auto['horsepower'] = Auto['horsepower'].replace('?', np.nan)

# Drop rows with NaN in horsepower or mpg
Auto_clean = Auto.dropna(subset=['horsepower', 'mpg']).copy()

# Convert to float
Auto_clean['horsepower'] = Auto_clean['horsepower'].astype(float)
Auto_clean['mpg'] = Auto_clean['mpg'].astype(float)


In [29]:
H = Auto_clean['horsepower'].values
Y = Auto_clean['mpg'].values


In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

cv_error = np.zeros(5)
for i, d in enumerate(range(1, 6)):
    X = np.power.outer(H, np.arange(d + 1))  # polynomial features: [1, H, H², ..., H^d]
    model = LinearRegression()
    M_CV = cross_validate(model, X, Y, cv=len(Y), scoring='neg_mean_squared_error')
    cv_error[i] = -np.mean(M_CV['test_score'])  # negate because scoring is negative MSE

print(cv_error)


[24.23151352 19.24821312 19.33498406 19.42443031 19.03321574]


In [31]:
import numpy as np

A = np.array([3, 5, 9])
B = np.array([2, 4])

result = np.add.outer(A, B)
print(result)


[[ 5  7]
 [ 7  9]
 [11 13]]
